version: '3'
services:
  service:
    image: messaging-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/messaging-service
      - spring.rabbitmq.host=rabbit
    depends_on:
      - postgres
      - rabbit
    ports:
    - 8080:8080
  postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messaging-service
    ports:
    - 5432:5432
  rabbit:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672