spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/messaging-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

rabbitmq:
  queue-name: messages
  exchange-name: messages.exchange
  routing-key: messages.routing.key